AllCops:
  NewCops: enable
  Exclude:
    - 'scratch/*.rb'
    - 'examples/*.rb'

Style/GlobalVars:
  Exclude:
    - 'utils/misc_utils.rb'

Style/RedundantException:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ConditionalAssignment:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/GuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'tests/test_midinote.rb'
    - 'tests/test_interval.rb'

Lint/AmbiguousOperator:
  Exclude:
    - 'tests/test_accum.rb'

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false
