AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'scratch/*.rb'
    - 'examples/*.rb'
    - 'yard/*.rb'

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedPatterns:
    - '^raise$'
    - '^yield$'
    - '_eval$'
  Exclude:
    - 'test/**/*.rb'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact
  Exclude:
    - 'test/**/*.rb'

Style/SymbolArray:
  Exclude:
    - 'test/**/*.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'test/**/*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Allow e.g. `module X; module Y; ...`. Look, I just refuse to start with like 8
# spaces of indentation by default.
Style/TrailingBodyOnModule:
  Enabled: false

# Require explicit classes when raising
Style/ImplicitRuntimeError:
  Enabled: true

# This bans explicit RuntimeError, which conflicts with ImplicitRuntimeError
Style/RedundantException:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false
