AllValidators:
  Exclude:
    - 'scratch/*'
    - 'test/*'
    - 'examples/*'
    - 'lib/spiseq/internal/*'
    - 'lib/spiseq/external/*'

  YardOptions: []

Tags/InformalNotation:
  Enabled: false

Tags/Order:
  Enabled: false

Tags/TagTypePosition:
  Enabled: false
