AllValidators:
  Exclude:
    - 'scratch/*'
    - 'tests/*'
    - 'examples/*'

  YardOptions: []

Tags/InformalNotation:
  Enabled: false

Tags/Order:
  Enabled: false

Tags/TagTypePosition:
  Enabled: false
